version: 2
jobs:
 dependencies:
  override:
    - curl -L -o google-chrome.deb https://s3.amazonaws.com/circle-downloads/google-chrome-stable_current_amd64_47.0.2526.73-1.deb
    - sudo dpkg -i google-chrome.deb
    - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
    - rm google-chrome.deb

 test:
  override:
    - google-chrome --version
    - mkdir -p $CIRCLE_TEST_REPORTS/cucumber
    - bundle exec rake features @CUCUMBER_TAGS=@login --format junit --out $CIRCLE_TEST_REPORTS/cucumber/junit.xml
